---
title: "Codis Territorials amb Lat Lon via csv"
author: "Xavier de Pedro"
date: "17/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require(pacman)) {install.packages(pacman)}; require(pacman)
p_load(rio)
p_load(stringr)
p_load(tidyverse)
p_load(janitor)

```

```{r}
path.csv.owncloud.codis.territorials <- "~/ownCloud/OMD-GID/CodisTerritorials"
path.csv.codis.territorials <- "codis_territorials"
#path.codis.extra <- "/windows/k/QUOTA/OMD/COMU/PROJECTES/19_001_BSC/dades/codis_territorials"
path.codis.extra <- file.path("codis_territorials", "vell")
list.files(path.csv.codis.territorials, pattern=".csv$", recursive = TRUE)
```

# Carrego latlong de centroides de provincies INE

```{r}
path.coords <- file.path(path.csv.codis.territorials, "geo/codis.int.csv")
codis.int <- read_csv(file.path(path.coords)) 
codis.int
```


# Add lat long to països

## Carrega GEO paisos

```{r}
gtp.paisos <- read_csv2(file.path(path.csv.codis.territorials, "CityOS/GTP_GEO_paisos.csv"))
gtp.paisos
```

```{r}
# nombre de provincies uniques
gtp.paisos.unique <- unique(gtp.paisos$ID_INE)
length(gtp.paisos.unique)
```

## Fem join de lon lat a gtp.paisos

```{r}
gtp.paisos.lj <- left_join(gtp.paisos, codis.int, by=c("ID_ISO_a2"="ISO2"))
str(gtp.paisos.lj)
```

## Mirem antijoins

```{r}
gtp.paisos.aj <- anti_join(gtp.paisos, codis.int, by=c("ID_ISO_a2"="ISO2"))
gtp.paisos.aj %>% distinct(ID_ISO_a2, .keep_all = TRUE)
```


```{r}
# Importem la fila per a Sudan del Sud
gtp.paisos.aj.sudansud <- rio::import(
  file.path(path.csv.codis.territorials, "CityOS/GTP_GEO_paisos_lonlat.antijoins_via_wikipedia.csv")
  )
gtp.paisos.aj.sudansud
```

```{r}
# Afegm les coordenades a totes les files que corresponen amb Sudan del Sud
gtp.paisos.lj <- gtp.paisos.lj %>% 
  mutate(
    LON = case_when(
      Pais == "Sudan del Sud, el" ~ 31.6,
      TRUE ~ LON),
    LAT = case_when(
      Pais == "Sudan del Sud, el" ~ 4.85,
      TRUE ~ LAT)
    )
gtp.paisos.lj %>% filter(is.na(LON))
```

```{r}
# Exportem resultats
# Left joins
write_csv(gtp.paisos.lj, file.path(path.csv.codis.territorials, "CityOS/GTP_GEO_paisos_lonlat.csv"))
write_csv(gtp.paisos.lj, file.path(path.csv.owncloud.codis.territorials, "CityOS/GTP_GEO_paisos_lonlat.csv"))

# antijoins unics
if (nrow(gtp.paisos.aj %>% distinct(ID_ISO_a2)) > 1) {
  write_csv(gtp.paisos.aj %>% distinct(ID_ISO_a2, .keep_all = TRUE),
            file.path(path.csv.codis.territorials, "CityOS/GTP_GEO_paisos_lonlat.antijoins.csv"))
  write_csv(gtp.paisos.aj %>% distinct(ID_ISO_a2, .keep_all = TRUE), 
            file.path(path.csv.owncloud.codis.territorials, "CityOS/GTP_GEO_paisos_lonlat.antijoin.csv"))
}

```



