---
title: "Codis Territorials amb Lat Lon via csv"
author: "Xavier de Pedro"
date: "17/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require(pacman)) {install.packages(pacman)}; require(pacman)
p_load(rio)
p_load(stringr)
p_load(tidyverse)
p_load(janitor)
```

```{r}
path.csv.owncloud.codis.territorials <- "~/ownCloud/OMD-GID/CodisTerritorials/"
path.csv.codis.territorials <- "codis_territorials/"
#path.codis.extra <- "/windows/k/QUOTA/OMD/COMU/PROJECTES/19_001_BSC/dades/codis_territorials/"
path.codis.extra <- file.path("codis_territorials", "vell")
list.files(path.csv.codis.territorials, pattern=".csv$", recursive = TRUE)
```

# Carrego latlong de centroides de municipis INE

```{r}
path.centroides.1 <- "codis_territorials/shp/ine.es/mun.ine.centroids.unique.cumun.wgs84.csv"
muni.ine.centroides.1 <- rio::import(file.path(path.centroides.1)) 
muni.ine.centroides.1
```


```{r}
# Codis latlong dels antijoins (gtp.muni.aj) de més avall, de codis ID_INE_NUM_Municipi_Curt que no trobavem pels centroides fet a partir dels shp de l'INE
path.centroides.2 <- "codis_territorials/shp/ine.es/mun.ine.wikipedia.extra.cumun.wgs84.csv"
muni.ine.centroides.2 <- rio::import(file.path(path.centroides.2)) 
muni.ine.centroides.2
```

```{r}
#ajuntem els dos data sets
muni.ine.centroides <- bind_rows(muni.ine.centroides.1, muni.ine.centroides.2)
muni.ine.centroides
#get_dupes(muni.ine.centroides, CUMUN)
```

# Add lat long to municipis

## Carrega GEO municipis

```{r}
gtp.muni <- rio::import(file.path(path.csv.codis.territorials, "CityOS/GTP_GEO_municipis_INE.csv"))
gtp.muni  %>% filter(Nom_Municipi=="Aceituna")
gtp.muni
```

```{r}
# nombre de municipis unics
gtp.muni.unique <- unique(gtp.muni$ID_INE_NUM_Municipi_Curt)
length(gtp.muni.unique)
```

## Fem join de lon lat a gtp.muni

```{r}
gtp.muni.lj <- left_join(gtp.muni, muni.ine.centroides, by=c("ID_INE_NUM_Municipi_Curt"="CUMUN"))
str(gtp.muni.lj)
```

## Mirem antijoins

```{r}
gtp.muni.aj <- anti_join(gtp.muni, muni.ine.centroides, by=c("ID_INE_NUM_Municipi_Curt"="CUMUN"))
gtp.muni.aj %>% distinct(ID_INE_NUM_Municipi_Curt, .keep_all = TRUE)
```

```{r}
# Exportem resultats
# Left joins
write_csv(gtp.muni.lj, file.path(path.csv.codis.territorials, "CityOS/GTP_GEO_municipis_INE_lonlat.csv"))
write_csv(gtp.muni.lj, file.path(path.csv.owncloud.codis.territorials, "CityOS/GTP_GEO_municipis_INE_lonlat.csv"))

if (nrow(gtp.muni.aj %>% distinct(ID_INE_NUM_Municipi_Curt)) > 0) {
  # antijoins unics
  write_csv(gtp.muni.aj %>% distinct(ID_INE_NUM_Municipi_Curt, .keep_all = TRUE), 
            file.path(path.csv.codis.territorials, "CityOS/GTP_GEO_municipis_INE_lonlat.antijoins.csv"))
  write_csv(gtp.muni.aj %>% distinct(ID_INE_NUM_Municipi_Curt, .keep_all = TRUE), 
          file.path(path.csv.owncloud.codis.territorials, "CityOS/GTP_GEO_municipis_INE_lonlat.antijoin.csv"))
}

```

